'use strict';window.DOMHandler=class{constructor(a,b){this._iRuntime=a;this._componentId=b;this._hasTickCallback=!1;this._tickCallback=()=>this.Tick()}Attach(){}PostToRuntime(a,b,c,d){this._iRuntime.PostToRuntimeComponent(this._componentId,a,b,c,d)}PostToRuntimeAsync(a,b,c,d){return this._iRuntime.PostToRuntimeComponentAsync(this._componentId,a,b,c,d)}_PostToRuntimeMaybeSync(a,b,c){this._iRuntime.UsesWorker()?this.PostToRuntime(a,b,c):this._iRuntime._GetLocalRuntime()._OnMessageFromDOM({type:"event",
component:this._componentId,handler:a,dispatchOpts:c||null,data:b,responseId:null})}AddRuntimeMessageHandler(a,b){this._iRuntime.AddRuntimeComponentMessageHandler(this._componentId,a,b)}AddRuntimeMessageHandlers(a){for(const [b,c]of a)this.AddRuntimeMessageHandler(b,c)}GetRuntimeInterface(){return this._iRuntime}GetComponentID(){return this._componentId}_StartTicking(){this._hasTickCallback||(this._iRuntime._AddRAFCallback(this._tickCallback),this._hasTickCallback=!0)}_StopTicking(){this._hasTickCallback&&
(this._iRuntime._RemoveRAFCallback(this._tickCallback),this._hasTickCallback=!1)}Tick(){}};
window.RateLimiter=class{constructor(a,b){this._callback=a;this._interval=b;this._timerId=-1;this._lastCallTime=-Infinity;this._timerCallFunc=()=>this._OnTimer();this._canRunImmediate=this._ignoreReset=!1}SetCanRunImmediate(a){this._canRunImmediate=!!a}Call(){if(-1===this._timerId){var a=Date.now(),b=a-this._lastCallTime,c=this._interval;b>=c&&this._canRunImmediate?(this._lastCallTime=a,this._RunCallback()):this._timerId=self.setTimeout(this._timerCallFunc,Math.max(c-b,4))}}_RunCallback(){this._ignoreReset=
!0;this._callback();this._ignoreReset=!1}Reset(){this._ignoreReset||(this._CancelTimer(),this._lastCallTime=Date.now())}_OnTimer(){this._timerId=-1;this._lastCallTime=Date.now();this._RunCallback()}_CancelTimer(){-1!==this._timerId&&(self.clearTimeout(this._timerId),this._timerId=-1)}Release(){this._CancelTimer();this._timerCallFunc=this._callback=null}};


'use strict';window.DOMElementHandler=class extends self.DOMHandler{constructor(a,b){super(a,b);this._elementMap=new Map;this._autoAttach=!0;this.AddRuntimeMessageHandler("create",a=>this._OnCreate(a));this.AddRuntimeMessageHandler("destroy",a=>this._OnDestroy(a));this.AddRuntimeMessageHandler("set-visible",a=>this._OnSetVisible(a));this.AddRuntimeMessageHandler("update-position",a=>this._OnUpdatePosition(a));this.AddRuntimeMessageHandler("update-state",a=>this._OnUpdateState(a));this.AddRuntimeMessageHandler("focus",
a=>this._OnSetFocus(a));this.AddRuntimeMessageHandler("set-css-style",a=>this._OnSetCssStyle(a));this.AddDOMElementMessageHandler("get-element",a=>a)}SetAutoAttach(a){this._autoAttach=!!a}AddDOMElementMessageHandler(a,b){this.AddRuntimeMessageHandler(a,a=>{const c=this._elementMap.get(a.elementId);return b(c,a)})}_OnCreate(a){const b=a.elementId,c=this.CreateElement(b,a);this._elementMap.set(b,c);a.isVisible||(c.style.display="none");this._autoAttach&&document.body.appendChild(c)}CreateElement(a,
b){throw Error("required override");}DestroyElement(a){}_OnDestroy(a){a=a.elementId;const b=this._elementMap.get(a);this.DestroyElement(b);this._autoAttach&&b.parentElement.removeChild(b);this._elementMap.delete(a)}PostToRuntimeElement(a,b,c){c||(c={});c.elementId=b;this.PostToRuntime(a,c)}_PostToRuntimeElementMaybeSync(a,b,c){c||(c={});c.elementId=b;this._PostToRuntimeMaybeSync(a,c)}_OnSetVisible(a){this._autoAttach&&(this._elementMap.get(a.elementId).style.display=a.isVisible?"":"none")}_OnUpdatePosition(a){if(this._autoAttach){var b=
this._elementMap.get(a.elementId);b.style.left=a.left+"px";b.style.top=a.top+"px";b.style.width=a.width+"px";b.style.height=a.height+"px";a=a.fontSize;null!==a&&(b.style.fontSize=a+"em")}}_OnUpdateState(a){const b=this._elementMap.get(a.elementId);this.UpdateState(b,a)}UpdateState(a,b){throw Error("required override");}_OnSetFocus(a){const b=this._elementMap.get(a.elementId);a.focus?b.focus():b.blur()}_OnSetCssStyle(a){this._elementMap.get(a.elementId).style[a.prop]=a.val}GetElementById(a){return this._elementMap.get(a)}};


'use strict';{var IsWebViewExportType=function(f){return w.has(f)},BlobToArrayBuffer=function(f){return new Promise((a,b)=>{const c=new FileReader;c.onload=b=>a(b.target.result);c.onerror=a=>b(a);c.readAsArrayBuffer(f)})},BlobToString=async function(f){f=await BlobToArrayBuffer(f);return(new TextDecoder("utf-8")).decode(f)},AddScript=function(f){if(f.isStringSrc){const a=document.createElement("script");a.async=!1;a.textContent=f.str;document.head.appendChild(a)}else return new Promise((a,b)=>{const c=
document.createElement("script");c.onload=a;c.onerror=b;c.async=!1;c.src=f;document.head.appendChild(c)})};const t=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let l=new Audio;const u={"audio/webm; codecs=opus":!!l.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!l.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!l.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!l.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!l.canPlayType("audio/mp4"),
"audio/mpeg":!!l.canPlayType("audio/mpeg")};l=null;const p=[];let m=0;window.RealFile=window.File;const n=[],q=new Map,r=new Map;let x=0;const v=[];self.runOnStartup=function(f){if("function"!==typeof f)throw Error("runOnStartup called without a function");v.push(f)};const w=new Set(["cordova","playable-ad","instant-games"]);window.RuntimeInterface=class f{constructor(a){this._useWorker=a.useWorker;this._messageChannelPort=null;this._baseUrl="";this._scriptFolder=a.scriptFolder;this._workerScriptBlobURLs=
{};this._localRuntime=this._worker=null;this._domHandlers=[];this._jobScheduler=this._canvas=this._runtimeDomHandler=null;this._rafId=-1;this._rafFunc=()=>this._OnRAFCallback();this._rafCallbacks=[];this._exportType=a.exportType;IsWebViewExportType(this._exportType)&&this._useWorker&&(console.warn("[C3 runtime] Worker mode is enabled and supported, but is disabled in WebViews due to crbug.com/923007. Reverting to DOM mode."),this._useWorker=!1);this._transferablesBroken=!1;this._localFileStrings=
this._localFileBlobs=null;"html5"!==this._exportType&&"playable-ad"!==this._exportType||"file"!==location.protocol.substr(0,4)||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");this.AddRuntimeComponentMessageHandler("runtime","cordova-fetch-local-file",a=>this._OnCordovaFetchLocalFile(a));this.AddRuntimeComponentMessageHandler("runtime","create-job-worker",a=>this._OnCreateJobWorker(a));
"cordova"===this._exportType?document.addEventListener("deviceready",()=>this._Init(a)):this._Init(a)}Release(){this._CancelAnimationFrame();this._messageChannelPort&&(this._messageChannelPort=this._messageChannelPort.onmessage=null);this._worker&&(this._worker.terminate(),this._worker=null);this._localRuntime&&(this._localRuntime.Release(),this._localRuntime=null);this._canvas&&(this._canvas.parentElement.removeChild(this._canvas),this._canvas=null)}GetCanvas(){return this._canvas}GetBaseURL(){return this._baseUrl}UsesWorker(){return this._useWorker}GetExportType(){return this._exportType}IsiOSCordova(){return t&&
"cordova"===this._exportType}IsiOSWebView(){return t&&IsWebViewExportType(this._exportType)||navigator.standalone}async _Init(a){if("playable-ad"===this._exportType){this._localFileBlobs=self.c3_base64files;this._localFileStrings={};await this._ConvertDataUrisToBlobs();for(let c=0,d=a.engineScripts.length;c<d;++c){var b=a.engineScripts[c].toLowerCase();this._localFileStrings.hasOwnProperty(b)?a.engineScripts[c]={isStringSrc:!0,str:this._localFileStrings[b]}:this._localFileBlobs.hasOwnProperty(b)&&
(a.engineScripts[c]=URL.createObjectURL(this._localFileBlobs[b]))}}a.baseUrl?this._baseUrl=a.baseUrl:(b=location.origin,this._baseUrl=("null"===b?"file:///":b)+location.pathname,b=this._baseUrl.lastIndexOf("/"),-1!==b&&(this._baseUrl=this._baseUrl.substr(0,b+1)));if(a.workerScripts)for(const [b,d]of Object.entries(a.workerScripts))this._workerScriptBlobURLs[b]=URL.createObjectURL(d);b=new MessageChannel;this._messageChannelPort=b.port1;this._messageChannelPort.onmessage=a=>this._OnMessageFromRuntime(a.data);
window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(a=>this._OnMessageFromDebugger(a));this._jobScheduler=new self.JobSchedulerDOM(this);await this._jobScheduler.Init();this.MaybeForceBodySize();"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();await this._TestTransferablesWork();this._useWorker?await this._InitWorker(a,b.port2):await this._InitDOM(a,b.port2)}_GetWorkerURL(a){return this._workerScriptBlobURLs.hasOwnProperty(a)?
this._workerScriptBlobURLs[a]:a.endsWith("/workermain.js")&&this._workerScriptBlobURLs.hasOwnProperty("workermain.js")?this._workerScriptBlobURLs["workermain.js"]:"playable-ad"===this._exportType&&this._localFileBlobs.hasOwnProperty(a.toLowerCase())?URL.createObjectURL(this._localFileBlobs[a.toLowerCase()]):a}async CreateWorker(a,b,c){if(a.startsWith("blob:"))return new Worker(a,c);if(this.IsiOSCordova()&&"file:"===location.protocol)return a=await this.CordovaFetchLocalFileAsArrayBuffer(this._scriptFolder+
a),a=new Blob([a],{type:"application/javascript"}),new Worker(URL.createObjectURL(a),c);a=new URL(a,b);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),c)}return new Worker(a,c)}MaybeForceBodySize(){if(this.IsiOSWebView()){const a=document.documentElement.style,b=document.body.style,c=window.innerWidth<window.innerHeight,d=c?window.screen.width:window.screen.height;b.height=a.height=(c?window.screen.height:
window.screen.width)+"px";b.width=a.width=d+"px"}}_GetCommonRuntimeOptions(a){return{baseUrl:this._baseUrl,windowInnerWidth:window.innerWidth,windowInnerHeight:window.innerHeight,devicePixelRatio:window.devicePixelRatio,isFullscreen:f.IsDocumentFullscreen(),projectData:a.projectData,previewImageBlobs:window.cr_previewImageBlobs||this._localFileBlobs,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,exportType:a.exportType,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.ife,jobScheduler:this._jobScheduler.GetPortData(),
supportedAudioFormats:u,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this._scriptFolder+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this._scriptFolder+"opus.wasm.wasm",isiOSCordova:this.IsiOSCordova(),isiOSWebView:this.IsiOSWebView(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async _InitWorker(a,b){var c=this._GetWorkerURL(a.workerMainUrl);this._worker=await this.CreateWorker(c,this._baseUrl,{name:"Runtime"});this._canvas=document.createElement("canvas");this._canvas.style.display=
"none";c=this._canvas.transferControlToOffscreen();document.body.appendChild(this._canvas);window.c3canvas=this._canvas;this._worker.postMessage(Object.assign(this._GetCommonRuntimeOptions(a),{type:"init-runtime",isInWorker:!0,messagePort:b,canvas:c,workerDependencyScripts:a.workerDependencyScripts||[],engineScripts:a.engineScripts,projectScripts:window.cr_allProjectScripts,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[b,c,...this._jobScheduler.GetPortTransferables()]);this._domHandlers=n.map(a=>
new a(this));this._FindRuntimeDOMHandler();self.c3_callFunction=(a,b)=>this._runtimeDomHandler._InvokeFunctionFromJS(a,b);"preview"===this._exportType&&(self.goToLastErrorScript=()=>this.PostToRuntimeComponent("runtime","go-to-last-error-script"))}async _InitDOM(a,b){this._canvas=document.createElement("canvas");this._canvas.style.display="none";document.body.appendChild(this._canvas);window.c3canvas=this._canvas;this._domHandlers=n.map(a=>new a(this));this._FindRuntimeDOMHandler();const c=a.engineScripts.map(a=>
"string"===typeof a?(new URL(a,this._baseUrl)).toString():a);Array.isArray(a.workerDependencyScripts)&&c.unshift(...a.workerDependencyScripts);await Promise.all(c.map(a=>AddScript(a)));if(a.projectScripts&&0<a.projectScripts.length){const b=self.C3_ProjectScriptsStatus;try{if(await Promise.all(a.projectScripts.map(a=>AddScript(a[1]))),Object.values(b).some(a=>!a)){self.setTimeout(()=>this._ReportProjectScriptError(b),100);return}}catch(e){console.error("[Preview] Error loading project scripts: ",
e);self.setTimeout(()=>this._ReportProjectScriptError(b),100);return}}"preview"===this._exportType&&"object"!==typeof self.C3.ScriptsInEvents?(console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this._GetCommonRuntimeOptions(a),{isInWorker:!1,messagePort:b,canvas:this._canvas,runOnStartupFunctions:v}),this._localRuntime=
self.C3_CreateRuntime(a),await self.C3_InitRuntime(this._localRuntime,a))}_ReportProjectScriptError(a){a=`Failed to load project script '${Object.entries(a).filter(a=>!a[1]).map(a=>a[0])[0]}'. Check all your JavaScript code has valid syntax.`;console.error("[Preview] "+a);alert(a)}async _OnCreateJobWorker(a){a=await this._jobScheduler._CreateJobWorker();return{outputPort:a,transferables:[a]}}_GetLocalRuntime(){if(this._useWorker)throw Error("not available in worker mode");return this._localRuntime}PostToRuntimeComponent(a,
b,c,d,e){this._messageChannelPort.postMessage({type:"event",component:a,handler:b,dispatchOpts:d||null,data:c,responseId:null},this._transferablesBroken?void 0:e)}PostToRuntimeComponentAsync(a,b,c,d,e){const g=x++,h=new Promise((a,b)=>{r.set(g,{resolve:a,reject:b})});this._messageChannelPort.postMessage({type:"event",component:a,handler:b,dispatchOpts:d||null,data:c,responseId:g},this._transferablesBroken?void 0:e);return h}["_OnMessageFromRuntime"](a){const b=a.type;if("event"===b)return this._OnEventFromRuntime(a);
if("result"===b)this._OnResultFromRuntime(a);else if("runtime-ready"===b)this._OnRuntimeReady();else if("alert"===b)alert(a.message);else throw Error(`unknown message '${b}'`);}_OnEventFromRuntime(a){const b=a.component,c=a.handler,d=a.data,e=a.responseId;if(a=q.get(b))if(a=a.get(c)){var g=null;try{g=a(d)}catch(h){console.error(`Exception in '${b}' handler '${c}':`,h);null!==e&&this._PostResultToRuntime(e,!1,""+h);return}if(null===e)return g;g&&g.then?g.then(a=>this._PostResultToRuntime(e,!0,a)).catch(a=>
{console.error(`Rejection from '${b}' handler '${c}':`,a);this._PostResultToRuntime(e,!1,""+a)}):this._PostResultToRuntime(e,!0,g)}else console.warn(`[DOM] No handler '${c}' for component '${b}'`);else console.warn(`[DOM] No event handlers for component '${b}'`)}_PostResultToRuntime(a,b,c){let d;c&&c.transferables&&(d=c.transferables);this._messageChannelPort.postMessage({type:"result",responseId:a,isOk:b,result:c},d)}_OnResultFromRuntime(a){const b=a.responseId,c=a.isOk;a=a.result;const d=r.get(b);
c?d.resolve(a):d.reject(a);r.delete(b)}AddRuntimeComponentMessageHandler(a,b,c){let d=q.get(a);d||(d=new Map,q.set(a,d));if(d.has(b))throw Error(`[DOM] Component '${a}' already has handler '${b}'`);d.set(b,c)}static AddDOMHandlerClass(a){if(n.includes(a))throw Error("DOM handler already added");n.push(a)}_FindRuntimeDOMHandler(){for(const a of this._domHandlers)if("runtime"===a.GetComponentID()){this._runtimeDomHandler=a;return}throw Error("cannot find runtime DOM handler");}_OnMessageFromDebugger(a){this.PostToRuntimeComponent("debugger",
"message",a)}_OnRuntimeReady(){for(const a of this._domHandlers)a.Attach()}static IsDocumentFullscreen(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement)}async GetRemotePreviewStatusInfo(){return await this.PostToRuntimeComponentAsync("runtime","get-remote-preview-status-info")}_AddRAFCallback(a){this._rafCallbacks.push(a);this._RequestAnimationFrame()}_RemoveRAFCallback(a){a=this._rafCallbacks.indexOf(a);if(-1===a)throw Error("invalid callback");
this._rafCallbacks.splice(a,1);this._rafCallbacks.length||this._CancelAnimationFrame()}_RequestAnimationFrame(){-1===this._rafId&&this._rafCallbacks.length&&(this._rafId=requestAnimationFrame(this._rafFunc))}_CancelAnimationFrame(){-1!==this._rafId&&(cancelAnimationFrame(this._rafId),this._rafId=-1)}_OnRAFCallback(){this._rafId=-1;for(const a of this._rafCallbacks)a();this._RequestAnimationFrame()}TryPlayMedia(a){this._runtimeDomHandler.TryPlayMedia(a)}RemovePendingPlay(a){this._runtimeDomHandler.RemovePendingPlay(a)}_PlayPendingMedia(){this._runtimeDomHandler._PlayPendingMedia()}SetSilent(a){this._runtimeDomHandler.SetSilent(a)}IsAudioFormatSupported(a){return!!u[a]}async _WasmDecodeWebMOpus(a){a=
await this.PostToRuntimeComponentAsync("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}IsAbsoluteURL(a){return/^(?:[a-z]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}IsRelativeURL(a){return!this.IsAbsoluteURL(a)}async _OnCordovaFetchLocalFile(a){const b=a.filename;switch(a.as){case "text":return await this.CordovaFetchLocalFileAsText(b);case "buffer":return await this.CordovaFetchLocalFileAsArrayBuffer(b);default:throw Error("unsupported type");}}_GetPermissionAPI(){const a=
window.cordova&&window.cordova.plugins&&window.cordova.plugins.permissions;if("object"!==typeof a)throw Error("Permission API is not loaded");return a}_MapPermissionID(a,b){a=a[b];if("string"!==typeof a)throw Error("Invalid permission name");return a}_HasPermission(a){const b=this._GetPermissionAPI();return new Promise((c,d)=>b.checkPermission(this._MapPermissionID(b,a),a=>c(!!a.hasPermission),d))}_RequestPermission(a){const b=this._GetPermissionAPI();return new Promise((c,d)=>b.requestPermission(this._MapPermissionID(b,
a),a=>c(!!a.hasPermission),d))}async RequestPermissions(a){if("cordova"!==this.GetExportType()||this.IsiOSCordova())return!0;for(const b of a)if(!await this._HasPermission(b)&&!1===await this._RequestPermission(b))return!1;return!0}async RequirePermissions(...a){if(!1===await this.RequestPermissions(a))throw Error("Permission not granted");}CordovaFetchLocalFile(a){const b=window.cordova.file.applicationDirectory+"www/"+a.toLowerCase();return new Promise((a,d)=>{window.resolveLocalFileSystemURL(b,
b=>{b.file(a,d)},d)})}async CordovaFetchLocalFileAsText(a){a=await this.CordovaFetchLocalFile(a);return await BlobToString(a)}_CordovaMaybeStartNextArrayBufferRead(){if(p.length&&!(8<=m)){m++;var a=p.shift();this._CordovaDoFetchLocalFileAsAsArrayBuffer(a.filename,a.successCallback,a.errorCallback)}}CordovaFetchLocalFileAsArrayBuffer(a){return new Promise((b,c)=>{p.push({filename:a,successCallback:a=>{m--;this._CordovaMaybeStartNextArrayBufferRead();b(a)},errorCallback:a=>{m--;this._CordovaMaybeStartNextArrayBufferRead();
c(a)}});this._CordovaMaybeStartNextArrayBufferRead()})}async _CordovaDoFetchLocalFileAsAsArrayBuffer(a,b,c){try{const c=await this.CordovaFetchLocalFile(a),e=await BlobToArrayBuffer(c);b(e)}catch(d){c(d)}}async _ConvertDataUrisToBlobs(){const a=[];for(const [b,c]of Object.entries(this._localFileBlobs))a.push(this._ConvertDataUriToBlobs(b,c));await Promise.all(a)}async _ConvertDataUriToBlobs(a,b){if("object"===typeof b)this._localFileBlobs[a]=new Blob([b.str],{type:b.type}),this._localFileStrings[a]=
b.str;else{let c=await this._FetchDataUri(b);c||(c=this._DataURIToBinaryBlobSync(b));this._localFileBlobs[a]=c}}async _FetchDataUri(a){try{return await (await fetch(a)).blob()}catch(b){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",b),null}}_DataURIToBinaryBlobSync(a){a=this._ParseDataURI(a);return this._BinaryStringToBlob(a.data,a.mime_type)}_ParseDataURI(a){var b=
a.indexOf(",");if(0>b)throw new URIError("expected comma in data: uri");var c=a.substring(5,b);a=a.substring(b+1);b=c.split(";");c=b[0]||"";const d=b[2];a="base64"===b[1]||"base64"===d?atob(a):decodeURIComponent(a);return{mime_type:c,data:a}}_BinaryStringToBlob(a,b){var c=a.length;let d=c>>2,e=new Uint8Array(c),g=new Uint32Array(e.buffer,0,d),h,k;for(k=h=0;h<d;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(c&=3;c--;)e[k]=a.charCodeAt(k),++k;return new Blob([e],
{type:b})}_TestTransferablesWork(){let a=null;const b=new Promise(b=>a=b),c=new ArrayBuffer(1),d=new MessageChannel;d.port2.onmessage=b=>{b.data&&b.data.arrayBuffer||(this._transferablesBroken=!0,console.warn("MessageChannel transfers determined to be broken. Disabling transferables."));a()};d.port1.postMessage({arrayBuffer:c},[c]);return b}}};


'use strict';{var KeyboardIsVisible=function(){const a=document.activeElement;if(!a)return!1;const b=a.tagName.toLowerCase(),c=new Set("email number password search tel text url".split(" "));return"textarea"===b?!0:"input"===b?c.has(a.type.toLowerCase()||"text"):IsInContentEditable(a)},ParentHasFocus=function(){try{return window.parent&&window.parent.document.hasFocus()}catch(a){return!1}},BlockWheelZoom=function(a){(a.metaKey||a.ctrlKey)&&a.preventDefault()},PreventDefaultOnCanvasOrDoc=function(a){const b=
a.target.tagName.toLowerCase();m.has(b)&&a.preventDefault()},IsInContentEditable=function(a){do{if(a.parentNode&&a.hasAttribute("contenteditable"))return!0;a=a.parentNode}while(a);return!1},BlobToSvgImage=async function(a,b,c){if(!/firefox/i.test(navigator.userAgent))return await BlobToImage(a);var d=await BlobToString(a);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const b=e.getAttribute("width"),d=e.getAttribute("height");
if(!b.includes("%")&&!d.includes("%"))return await BlobToImage(a)}e.setAttribute("width",b+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);a=new Blob([d],{type:"image/svg+xml"});return await BlobToImage(a)},BlobToString=function(a){return new Promise((b,c)=>{let d=new FileReader;d.onload=a=>b(a.target.result);d.onerror=a=>c(a);d.readAsText(a)})},BlobToImage=async function(a){a=URL.createObjectURL(a);try{return await FetchImage(a)}finally{URL.revokeObjectURL(a)}},FetchImage=
function(a){return new Promise((b,c)=>{const d=new Image;d.onload=()=>b(d);d.onerror=a=>c(a);d.src=a})},AddStyleSheet=function(a){return new Promise((b,c)=>{const d=document.createElement("link");d.onload=()=>b(d);d.onerror=a=>c(a);d.rel="stylesheet";d.href=a;document.head.appendChild(d)})},IsCompatibilityMouseEvent=function(a){return a.sourceCapabilities&&a.sourceCapabilities.firesTouchEvents||a.originalEvent&&a.originalEvent.sourceCapabilities&&a.originalEvent.sourceCapabilities.firesTouchEvents};
const h=self.RuntimeInterface,n=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),f={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},l={dispatchUserScriptEvent:!0},p={dispatchRuntimeEvent:!0},m=new Set(["canvas","body","html"]);self.C3_GetSvgImageSize=async function(a){a=await BlobToImage(a);if(0<a.width&&0<a.height)return[a.width,a.height];{a.style.position="absolute";a.style.left="0px";a.style.top="0px";a.style.visibility="hidden";document.body.appendChild(a);const b=a.getBoundingClientRect();
document.body.removeChild(a);return[b.width,b.height]}};self.C3_RasterSvgImageBlob=async function(a,b,c,d,e){a=await BlobToSvgImage(a,b,c);const g=document.createElement("canvas");g.width=d;g.height=e;g.getContext("2d").drawImage(a,0,0,b,c);return g};let k=!1;document.addEventListener("pause",()=>k=!0);document.addEventListener("resume",()=>k=!1);h.AddDOMHandlerClass(class extends self.DOMHandler{constructor(a){super(a,"runtime");this._isFirstSizeUpdate=!0;this._simulatedResizeTimerId=-1;this._targetOrientation=
"any";this._attachedDeviceMotionEvent=this._attachedDeviceOrientationEvent=!1;this._lastPointerRawUpdateEvent=this._pointerRawUpdateRateLimiter=this._debugHighlightElem=null;a.AddRuntimeComponentMessageHandler("canvas","update-size",a=>this._OnUpdateCanvasSize(a));a.AddRuntimeComponentMessageHandler("runtime","invoke-download",a=>this._OnInvokeDownload(a));a.AddRuntimeComponentMessageHandler("runtime","raster-svg-image",a=>this._OnRasterSvgImage(a));a.AddRuntimeComponentMessageHandler("runtime","get-svg-image-size",
a=>this._OnGetSvgImageSize(a));a.AddRuntimeComponentMessageHandler("runtime","set-target-orientation",a=>this._OnSetTargetOrientation(a));a.AddRuntimeComponentMessageHandler("runtime","register-sw",()=>this._OnRegisterSW());a.AddRuntimeComponentMessageHandler("runtime","post-to-debugger",a=>this._OnPostToDebugger(a));a.AddRuntimeComponentMessageHandler("runtime","go-to-script",a=>this._OnPostToDebugger(a));a.AddRuntimeComponentMessageHandler("runtime","before-start-ticking",()=>this._OnBeforeStartTicking());
a.AddRuntimeComponentMessageHandler("runtime","debug-highlight",a=>this._OnDebugHighlight(a));a.AddRuntimeComponentMessageHandler("runtime","enable-device-orientation",()=>this._AttachDeviceOrientationEvent());a.AddRuntimeComponentMessageHandler("runtime","enable-device-motion",()=>this._AttachDeviceMotionEvent());a.AddRuntimeComponentMessageHandler("runtime","add-stylesheet",a=>this._OnAddStylesheet(a));a.AddRuntimeComponentMessageHandler("runtime","alert",a=>this._OnAlert(a));const b=new Set(["input",
"textarea","datalist"]);window.addEventListener("contextmenu",a=>{const c=a.target,d=c.tagName.toLowerCase();b.has(d)||IsInContentEditable(c)||a.preventDefault()});const c=a.GetCanvas();window.addEventListener("selectstart",PreventDefaultOnCanvasOrDoc);window.addEventListener("gesturehold",PreventDefaultOnCanvasOrDoc);c.addEventListener("selectstart",PreventDefaultOnCanvasOrDoc);c.addEventListener("gesturehold",PreventDefaultOnCanvasOrDoc);window.addEventListener("touchstart",PreventDefaultOnCanvasOrDoc,
{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",PreventDefaultOnCanvasOrDoc,{passive:!1}),c.addEventListener("pointerdown",PreventDefaultOnCanvasOrDoc)):c.addEventListener("touchstart",PreventDefaultOnCanvasOrDoc);this._mousePointerLastButtons=0;window.addEventListener("mousedown",a=>{1===a.button&&a.preventDefault()});window.addEventListener("mousewheel",BlockWheelZoom,{passive:!1});window.addEventListener("wheel",BlockWheelZoom,{passive:!1});window.addEventListener("resize",
()=>this._OnWindowResize());a.IsiOSWebView()&&window.addEventListener("focusout",()=>{KeyboardIsVisible()||(document.scrollingElement.scrollTop=0)});this._mediaPendingPlay=new Set;this._mediaRemovedPendingPlay=new WeakSet;this._isSilent=!1}_OnBeforeStartTicking(){"cordova"===this._iRuntime.GetExportType()?(document.addEventListener("pause",()=>this._OnVisibilityChange(!0)),document.addEventListener("resume",()=>this._OnVisibilityChange(!1))):document.addEventListener("visibilitychange",()=>this._OnVisibilityChange(document.hidden));
return{isSuspended:!(!document.hidden&&!k)}}Attach(){window.addEventListener("focus",()=>this._PostRuntimeEvent("window-focus"));window.addEventListener("blur",()=>{this._PostRuntimeEvent("window-blur",{parentHasFocus:ParentHasFocus()});this._mousePointerLastButtons=0});window.addEventListener("fullscreenchange",()=>this._OnFullscreenChange());window.addEventListener("webkitfullscreenchange",()=>this._OnFullscreenChange());window.addEventListener("mozfullscreenchange",()=>this._OnFullscreenChange());
window.addEventListener("fullscreenerror",a=>this._OnFullscreenError(a));window.addEventListener("webkitfullscreenerror",a=>this._OnFullscreenError(a));window.addEventListener("mozfullscreenerror",a=>this._OnFullscreenError(a));window.addEventListener("keydown",a=>this._OnKeyEvent("keydown",a));window.addEventListener("keyup",a=>this._OnKeyEvent("keyup",a));window.addEventListener("dblclick",a=>this._OnMouseEvent("dblclick",a,f));window.addEventListener("wheel",a=>this._OnMouseWheelEvent("wheel",
a));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",a=>{this._HandlePointerDownFocus(a);this._OnPointerEvent("pointerdown",a)}),this._iRuntime.UsesWorker()&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this._pointerRawUpdateRateLimiter=new self.RateLimiter(()=>this._DoSendPointerRawUpdate(),5),this._pointerRawUpdateRateLimiter.SetCanRunImmediate(!0),window.addEventListener("pointerrawupdate",a=>this._OnPointerRawUpdate(a))):window.addEventListener("pointermove",
a=>this._OnPointerEvent("pointermove",a)),window.addEventListener("pointerup",a=>this._OnPointerEvent("pointerup",a)),window.addEventListener("pointercancel",a=>this._OnPointerEvent("pointercancel",a))):(window.addEventListener("mousedown",a=>{this._HandlePointerDownFocus(a);this._OnMouseEventAsPointer("pointerdown",a)}),window.addEventListener("mousemove",a=>this._OnMouseEventAsPointer("pointermove",a)),window.addEventListener("mouseup",a=>this._OnMouseEventAsPointer("pointerup",a)),window.addEventListener("touchstart",
a=>{this._HandlePointerDownFocus(a);this._OnTouchEvent("pointerdown",a)}),window.addEventListener("touchmove",a=>this._OnTouchEvent("pointermove",a)),window.addEventListener("touchend",a=>this._OnTouchEvent("pointerup",a)),window.addEventListener("touchcancel",a=>this._OnTouchEvent("pointercancel",a)));const a=()=>this._PlayPendingMedia();window.addEventListener("pointerup",a,!0);window.addEventListener("touchend",a,!0);window.addEventListener("click",a,!0);window.addEventListener("keydown",a,!0);
window.addEventListener("gamepadconnected",a,!0)}_PostRuntimeEvent(a,b){this.PostToRuntime(a,b||null,p)}_GetWindowInnerWidth(){return Math.max(window.innerWidth,1)}_GetWindowInnerHeight(){return Math.max(window.innerHeight,1)}_OnWindowResize(){const a=this._GetWindowInnerWidth(),b=this._GetWindowInnerHeight();this._PostRuntimeEvent("window-resize",{innerWidth:a,innerHeight:b,devicePixelRatio:window.devicePixelRatio});this._iRuntime.IsiOSWebView()&&(-1!==this._simulatedResizeTimerId&&clearTimeout(this._simulatedResizeTimerId),
this._OnSimulatedResize(a,b,0))}_ScheduleSimulatedResize(a,b,c){-1!==this._simulatedResizeTimerId&&clearTimeout(this._simulatedResizeTimerId);this._simulatedResizeTimerId=setTimeout(()=>this._OnSimulatedResize(a,b,c),48)}_OnSimulatedResize(a,b,c){const d=this._GetWindowInnerWidth(),e=this._GetWindowInnerHeight();this._simulatedResizeTimerId=-1;d!=a||e!=b?this._PostRuntimeEvent("window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio}):10>c&&this._ScheduleSimulatedResize(d,
e,c+1)}_OnSetTargetOrientation(a){this._targetOrientation=a.targetOrientation}_TrySetTargetOrientation(){const a=this._targetOrientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(a).catch(a=>console.warn("[Construct 3] Failed to lock orientation: ",a));else try{let b=!1;screen.lockOrientation?b=screen.lockOrientation(a):screen.webkitLockOrientation?b=screen.webkitLockOrientation(a):screen.mozLockOrientation?b=screen.mozLockOrientation(a):screen.msLockOrientation&&(b=screen.msLockOrientation(a));
b||console.warn("[Construct 3] Failed to lock orientation")}catch(b){console.warn("[Construct 3] Failed to lock orientation: ",b)}}_OnFullscreenChange(){const a=h.IsDocumentFullscreen();a&&"any"!==this._targetOrientation&&this._TrySetTargetOrientation();this.PostToRuntime("fullscreenchange",{isFullscreen:a,innerWidth:this._GetWindowInnerWidth(),innerHeight:this._GetWindowInnerHeight()})}_OnFullscreenError(a){console.warn("[Construct 3] Fullscreen request failed: ",a);this.PostToRuntime("fullscreenerror",
{isFullscreen:h.IsDocumentFullscreen(),innerWidth:this._GetWindowInnerWidth(),innerHeight:this._GetWindowInnerHeight()})}_OnVisibilityChange(a){a?this._iRuntime._CancelAnimationFrame():this._iRuntime._RequestAnimationFrame();this.PostToRuntime("visibilitychange",{hidden:a})}_OnKeyEvent(a,b){"Backspace"===b.key&&PreventDefaultOnCanvasOrDoc(b);const c=n.get(b.code)||b.code;this._PostToRuntimeMaybeSync(a,{code:c,key:b.key,which:b.which,repeat:b.repeat,altKey:b.altKey,ctrlKey:b.ctrlKey,metaKey:b.metaKey,
shiftKey:b.shiftKey,timeStamp:b.timeStamp},f)}_OnMouseWheelEvent(a,b){this.PostToRuntime(a,{clientX:b.clientX,clientY:b.clientY,pageX:b.pageX,pageY:b.pageY,deltaX:b.deltaX,deltaY:b.deltaY,deltaZ:b.deltaZ,deltaMode:b.deltaMode,timeStamp:b.timeStamp},f)}_OnMouseEvent(a,b,c){IsCompatibilityMouseEvent(b)||this._PostToRuntimeMaybeSync(a,{button:b.button,buttons:b.buttons,clientX:b.clientX,clientY:b.clientY,pageX:b.pageX,pageY:b.pageY,timeStamp:b.timeStamp},c)}_OnMouseEventAsPointer(a,b){if(!IsCompatibilityMouseEvent(b)){var c=
this._mousePointerLastButtons;"pointerdown"===a&&0!==c?a="pointermove":"pointerup"===a&&0!==b.buttons&&(a="pointermove");this._PostToRuntimeMaybeSync(a,{pointerId:1,pointerType:"mouse",button:b.button,buttons:b.buttons,lastButtons:c,clientX:b.clientX,clientY:b.clientY,pageX:b.pageX,pageY:b.pageY,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:b.timeStamp},f);this._mousePointerLastButtons=b.buttons;this._OnMouseEvent(b.type,b,l)}}_OnPointerEvent(a,b){this._pointerRawUpdateRateLimiter&&
"pointermove"!==a&&this._pointerRawUpdateRateLimiter.Reset();var c=0;"mouse"===b.pointerType&&(c=this._mousePointerLastButtons);this._PostToRuntimeMaybeSync(a,{pointerId:b.pointerId,pointerType:b.pointerType,button:b.button,buttons:b.buttons,lastButtons:c,clientX:b.clientX,clientY:b.clientY,pageX:b.pageX,pageY:b.pageY,width:b.width||0,height:b.height||0,pressure:b.pressure||0,tangentialPressure:b.tangentialPressure||0,tiltX:b.tiltX||0,tiltY:b.tiltY||0,twist:b.twist||0,timeStamp:b.timeStamp},f);"mouse"===
b.pointerType&&(c="mousemove","pointerdown"===a?c="mousedown":"pointerup"===a&&(c="pointerup"),this._OnMouseEvent(c,b,l),this._mousePointerLastButtons=b.buttons)}_OnPointerRawUpdate(a){this._lastPointerRawUpdateEvent=a;this._pointerRawUpdateRateLimiter.Call()}_DoSendPointerRawUpdate(){this._OnPointerEvent("pointermove",this._lastPointerRawUpdateEvent);this._lastPointerRawUpdateEvent=null}_OnTouchEvent(a,b){for(let c=0,d=b.changedTouches.length;c<d;++c){const d=b.changedTouches[c];this._PostToRuntimeMaybeSync(a,
{pointerId:d.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:d.clientX,clientY:d.clientY,pageX:d.pageX,pageY:d.pageY,width:2*(d.radiusX||d.webkitRadiusX||0),height:2*(d.radiusY||d.webkitRadiusY||0),pressure:d.force||d.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:d.rotationAngle||0,timeStamp:b.timeStamp},f)}}_HandlePointerDownFocus(a){window!==window.top&&window.focus();this._IsElementCanvasOrDocument(a.target)&&document.activeElement&&!this._IsElementCanvasOrDocument(document.activeElement)&&
document.activeElement.blur()}_IsElementCanvasOrDocument(a){return!a||a===document||a===window||a===document.body||"canvas"===a.tagName.toLowerCase()}_AttachDeviceOrientationEvent(){this._attachedDeviceOrientationEvent||(this._attachedDeviceOrientationEvent=!0,window.addEventListener("deviceorientation",a=>this._OnDeviceOrientation(a)))}_AttachDeviceMotionEvent(){this._attachedDeviceMotionEvent||(this._attachedDeviceMotionEvent=!0,window.addEventListener("devicemotion",a=>this._OnDeviceMotion(a)))}_OnDeviceOrientation(a){this.PostToRuntime("deviceorientation",
{alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},f)}_OnDeviceMotion(a){let b=null;var c=a.acceleration;c&&(b={x:c.x||0,y:c.y||0,z:c.z||0});c=null;var d=a.accelerationIncludingGravity;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;const e=a.rotationRate;e&&(d={alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0});this.PostToRuntime("devicemotion",{acceleration:b,accelerationIncludingGravity:c,rotationRate:d,interval:a.interval,timeStamp:a.timeStamp},f)}_OnUpdateCanvasSize(a){const b=
this.GetRuntimeInterface(),c=b.GetCanvas();c.style.width=a.styleWidth+"px";c.style.height=a.styleHeight+"px";c.style.marginLeft=a.marginLeft+"px";c.style.marginTop=a.marginTop+"px";b.MaybeForceBodySize();this._isFirstSizeUpdate&&(c.style.display="",this._isFirstSizeUpdate=!1)}_OnInvokeDownload(a){const b=a.url;a=a.filename;const c=document.createElement("a"),d=document.body;c.textContent=a;c.href=b;c.download=a;d.appendChild(c);c.click();d.removeChild(c)}async _OnRasterSvgImage(a){var b=a.imageBitmapOpts;
a=await self.C3_RasterSvgImageBlob(a.blob,a.imageWidth,a.imageHeight,a.surfaceWidth,a.surfaceHeight);b=b?await createImageBitmap(a,b):await createImageBitmap(a);return{imageBitmap:b,transferables:[b]}}async _OnGetSvgImageSize(a){return await self.C3_GetSvgImageSize(a.blob)}async _OnAddStylesheet(a){await AddStyleSheet(a.url)}_PlayPendingMedia(){var a=[...this._mediaPendingPlay];this._mediaPendingPlay.clear();if(!this._isSilent)for(const b of a)(a=b.play())&&a.catch(a=>{this._mediaRemovedPendingPlay.has(b)||
this._mediaPendingPlay.add(b)})}TryPlayMedia(a){if("function"!==typeof a.play)throw Error("missing play function");this._mediaRemovedPendingPlay.delete(a);let b;try{b=a.play()}catch(c){this._mediaPendingPlay.add(a);return}b&&b.catch(b=>{this._mediaRemovedPendingPlay.has(a)||this._mediaPendingPlay.add(a)})}RemovePendingPlay(a){this._mediaPendingPlay.delete(a);this._mediaRemovedPendingPlay.add(a)}SetSilent(a){this._isSilent=!!a}_OnDebugHighlight(a){if(a.show){this._debugHighlightElem||(this._debugHighlightElem=
document.createElement("div"),this._debugHighlightElem.id="inspectOutline",document.body.appendChild(this._debugHighlightElem));var b=this._debugHighlightElem;b.style.display="";b.style.left=a.left-1+"px";b.style.top=a.top-1+"px";b.style.width=a.width+2+"px";b.style.height=a.height+2+"px";b.textContent=a.name}else this._debugHighlightElem&&(this._debugHighlightElem.style.display="none")}_OnRegisterSW(){window.C3_RegisterSW&&window.C3_RegisterSW()}_OnPostToDebugger(a){window.c3_postToMessagePort&&
(a.from="runtime",window.c3_postToMessagePort(a))}_InvokeFunctionFromJS(a,b){return this.PostToRuntimeAsync("js-invoke-function",{name:a,params:b})}_OnAlert(a){alert(a.message)}})};


'use strict';{const d=document.currentScript.src;self.JobSchedulerDOM=class{constructor(a){this._runtimeInterface=a;this._baseUrl=d?d.substr(0,d.lastIndexOf("/")+1):a.GetBaseURL();this._maxNumWorkers=Math.min(navigator.hardwareConcurrency||2,16);this._dispatchWorker=null;this._jobWorkers=[];this._outputPort=this._inputPort=null}async Init(){if(this._hasInitialised)throw Error("already initialised");this._hasInitialised=!0;var a=this._runtimeInterface._GetWorkerURL("dispatchworker.js");this._dispatchWorker=
await this._runtimeInterface.CreateWorker(a,this._baseUrl,{name:"DispatchWorker"});a=new MessageChannel;this._inputPort=a.port1;this._dispatchWorker.postMessage({type:"_init","in-port":a.port2},[a.port2]);this._outputPort=await this._CreateJobWorker()}async _CreateJobWorker(){const a=this._jobWorkers.length;var b=this._runtimeInterface._GetWorkerURL("jobworker.js");b=await this._runtimeInterface.CreateWorker(b,this._baseUrl,{name:"JobWorker"+a});const c=new MessageChannel,e=new MessageChannel;this._dispatchWorker.postMessage({type:"_addJobWorker",
port:c.port1},[c.port1]);b.postMessage({type:"init",number:a,"dispatch-port":c.port2,"output-port":e.port2},[c.port2,e.port2]);this._jobWorkers.push(b);return e.port1}GetPortData(){return{inputPort:this._inputPort,outputPort:this._outputPort,maxNumWorkers:this._maxNumWorkers}}GetPortTransferables(){return[this._inputPort,this._outputPort]}}};


'use strict';if(window.C3_IsSupported){const a="undefined"!==typeof OffscreenCanvas;window.c3_runtimeInterface=new self.RuntimeInterface({useWorker:true&&a,workerMainUrl:"workermain.js",engineScripts:["scripts/c3runtime.js"],scriptFolder:"scripts/",workerDependencyScripts:[],exportType:"html5"})};
'use strict';var equalsNoCase=function(a,b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()};
self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMHandler{constructor(a){super(a,"audio");this._destinationNode=this._audioContext=null;this._hasAttachedUnblockEvents=this._hasUnblocked=!1;this._unblockFunc=()=>this._UnblockAudioContext();this._audioBuffers=[];this._audioInstances=[];this._lastAudioInstance=null;this._lastPlayedTag="";this._lastTickCount=-1;this._pendingTags=new Map;this._masterVolume=1;this._isSilent=!1;this._timeScaleMode=0;this._timeScale=1;this._gameTime=0;this._panningModel=
"HRTF";this._distanceModel="inverse";this._refDistance=600;this._maxDistance=1E4;this._rolloffFactor=1;this._hasAnySoftwareDecodedMusic=this._playMusicAsSound=!1;this._supportsWebMOpus=this._iRuntime.IsAudioFormatSupported("audio/webm; codecs=opus");this._effects=new Map;this._analysers=new Set;this._isPendingPostFxState=!1;this._microphoneTag="";this._microphoneSource=null;self.C3Audio_OnMicrophoneStream=(a,c)=>this._OnMicrophoneStream(a,c);this._destMediaStreamNode=null;self.C3Audio_GetOutputStream=
()=>this._OnGetOutputStream();self.C3Audio_DOMInterface=this;this.AddRuntimeMessageHandlers([["create-audio-context",a=>this._CreateAudioContext(a)],["play",a=>this._Play(a)],["stop",a=>this._Stop(a)],["stop-all",()=>this._StopAll()],["set-paused",a=>this._SetPaused(a)],["set-volume",a=>this._SetVolume(a)],["fade-volume",a=>this._FadeVolume(a)],["set-master-volume",a=>this._SetMasterVolume(a)],["set-muted",a=>this._SetMuted(a)],["set-silent",a=>this._SetSilent(a)],["set-looping",a=>this._SetLooping(a)],
["set-playback-rate",a=>this._SetPlaybackRate(a)],["seek",a=>this._Seek(a)],["preload",a=>this._Preload(a)],["unload",a=>this._Unload(a)],["unload-all",()=>this._UnloadAll()],["set-suspended",a=>this._SetSuspended(a)],["add-effect",a=>this._AddEffect(a)],["set-effect-param",a=>this._SetEffectParam(a)],["remove-effects",a=>this._RemoveEffects(a)],["tick",a=>this._OnTick(a)],["load-state",a=>this._OnLoadState(a)]])}async _CreateAudioContext(a){a.isiOSCordova&&(this._playMusicAsSound=!0);this._timeScaleMode=
a.timeScaleMode;this._panningModel=["equalpower","HRTF","soundfield"][a.panningModel];this._distanceModel=["linear","inverse","exponential"][a.distanceModel];this._refDistance=a.refDistance;this._maxDistance=a.maxDistance;this._rolloffFactor=a.rolloffFactor;var b={latencyHint:a.latencyHint};if("undefined"!==typeof AudioContext)this._audioContext=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this._audioContext=new webkitAudioContext(b);else throw Error("Web Audio API not supported");
this._AttachUnblockEvents();this._audioContext.onstatechange=()=>{"running"!==this._audioContext.state&&this._AttachUnblockEvents()};this._destinationNode=this._audioContext.createGain();this._destinationNode.connect(this._audioContext.destination);b=a.listenerPos;this._audioContext.listener.setPosition(b[0],b[1],b[2]);this._audioContext.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>this.GetAudioCurrentTime();try{await Promise.all(a.preloadList.map(a=>this._GetAudioBuffer(a.originalUrl,
a.url,a.type,!1)))}catch(c){console.error("[Construct 3] Preloading sounds failed: ",c)}return{sampleRate:this._audioContext.sampleRate}}_AttachUnblockEvents(){this._hasAttachedUnblockEvents||(this._hasUnblocked=!1,window.addEventListener("pointerup",this._unblockFunc,!0),window.addEventListener("touchend",this._unblockFunc,!0),window.addEventListener("click",this._unblockFunc,!0),window.addEventListener("keydown",this._unblockFunc,!0),this._hasAttachedUnblockEvents=!0)}_DetachUnblockEvents(){this._hasAttachedUnblockEvents&&
(this._hasUnblocked=!0,window.removeEventListener("pointerup",this._unblockFunc,!0),window.removeEventListener("touchend",this._unblockFunc,!0),window.removeEventListener("click",this._unblockFunc,!0),window.removeEventListener("keydown",this._unblockFunc,!0),this._hasAttachedUnblockEvents=!1)}_UnblockAudioContext(){if(!this._hasUnblocked){var a=this._audioContext;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),c=a.createBufferSource();c.buffer=b;c.connect(a.destination);
c.start(0);"running"===a.state&&this._DetachUnblockEvents()}}GetAudioContext(){return this._audioContext}GetAudioCurrentTime(){return this._audioContext.currentTime}GetDestinationNode(){return this._destinationNode}GetDestinationForTag(a){return(a=this._effects.get(a.toLowerCase()))?a[0].GetInputNode():this.GetDestinationNode()}AddEffectForTag(a,b){a=a.toLowerCase();let c=this._effects.get(a);c||(c=[],this._effects.set(a,c));b._SetIndex(c.length);b._SetTag(a);c.push(b);this._ReconnectEffects(a)}_ReconnectEffects(a){let b=
this.GetDestinationNode();const c=this._effects.get(a);if(c&&c.length){b=c[0].GetInputNode();for(let a=0,b=c.length;a<b;++a){const d=c[a];a+1===b?d.ConnectTo(this.GetDestinationNode()):d.ConnectTo(c[a+1].GetInputNode())}}for(const c of this.audioInstancesByTag(a))c.Reconnect(b);this._microphoneSource&&this._microphoneTag===a&&(this._microphoneSource.disconnect(),this._microphoneSource.connect(b))}GetMasterVolume(){return this._masterVolume}IsSilent(){return this._isSilent}GetTimeScaleMode(){return this._timeScaleMode}GetTimeScale(){return this._timeScale}GetGameTime(){return this._gameTime}IsPlayMusicAsSound(){return this._playMusicAsSound}SupportsWebMOpus(){return this._supportsWebMOpus}_SetHasAnySoftwareDecodedMusic(){this._hasAnySoftwareDecodedMusic=
!0}GetPanningModel(){return this._panningModel}GetDistanceModel(){return this._distanceModel}GetReferenceDistance(){return this._refDistance}GetMaxDistance(){return this._maxDistance}GetRolloffFactor(){return this._rolloffFactor}DecodeAudioData(a,b){return b?this._iRuntime._WasmDecodeWebMOpus(a).then(a=>{const b=this._audioContext.createBuffer(1,a.length,48E3);b.getChannelData(0).set(a);return b}):new Promise((b,d)=>{this._audioContext.decodeAudioData(a,b,d)})}TryPlayMedia(a){this._iRuntime.TryPlayMedia(a)}RemovePendingPlay(a){this._iRuntime.RemovePendingPlay(a)}ReleaseInstancesForBuffer(a){let b=
0;for(let c=0,d=this._audioInstances.length;c<d;++c){const d=this._audioInstances[c];this._audioInstances[b]=d;d.GetBuffer()===a?d.Release():++b}this._audioInstances.length=b}ReleaseAllMusicBuffers(){let a=0;for(let b=0,c=this._audioBuffers.length;b<c;++b){const c=this._audioBuffers[b];this._audioBuffers[a]=c;c.IsMusic()?c.Release():++a}this._audioBuffers.length=a}*audioInstancesByTag(a){if(a)for(const b of this._audioInstances)equalsNoCase(b.GetTag(),a)&&(yield b);else this._lastAudioInstance&&!this._lastAudioInstance.HasEnded()&&
(yield this._lastAudioInstance)}async _GetAudioBuffer(a,b,c,d,e){for(const a of this._audioBuffers)if(a.GetUrl()===b)return await a.Load(),a;if(e)return null;d&&(this._playMusicAsSound||this._hasAnySoftwareDecodedMusic)&&this.ReleaseAllMusicBuffers();a=self.C3AudioBuffer.Create(this,a,b,c,d);this._audioBuffers.push(a);await a.Load();return a}async _GetAudioInstance(a,b,c,d,e){for(const a of this._audioInstances)if(a.GetUrl()===b&&(a.CanBeRecycled()||e))return a.SetTag(d),a;a=(await this._GetAudioBuffer(a,
b,c,e)).CreateInstance(d);this._audioInstances.push(a);return a}_AddPendingTag(a){let b=this._pendingTags.get(a);if(!b){let c=null;b={pendingCount:0,promise:new Promise(a=>c=a),resolve:c};this._pendingTags.set(a,b)}b.pendingCount++}_RemovePendingTag(a){const b=this._pendingTags.get(a);if(!b)throw Error("expected pending tag");b.pendingCount--;0===b.pendingCount&&(b.resolve(),this._pendingTags.delete(a))}TagReady(a){a||(a=this._lastPlayedTag);return(a=this._pendingTags.get(a))?a.promise:Promise.resolve()}_MaybeStartTicking(){if(0<
this._analysers.size)this._StartTicking();else for(const a of this._audioInstances)if(a.IsActive()){this._StartTicking();break}}Tick(){for(var a of this._analysers)a.Tick();a=this.GetAudioCurrentTime();for(var b of this._audioInstances)b.Tick(a);b=this._audioInstances.filter(a=>a.IsActive()).map(a=>a.GetState());this.PostToRuntime("state",{tickCount:this._lastTickCount,audioInstances:b,analysers:[...this._analysers].map(a=>a.GetData())});0===b.length&&0===this._analysers.size&&this._StopTicking()}PostTrigger(a,
b,c){this.PostToRuntime("trigger",{type:a,tag:b,aiid:c})}async _Play(a){const b=a.originalUrl,c=a.url,d=a.type,e=a.isMusic,g=a.tag,k=a.isLooping,l=a.vol,m=a.pos,f=a.panning;let h=a.off;0<h&&!a.trueClock&&(this._audioContext.getOutputTimestamp?(a=this._audioContext.getOutputTimestamp(),h=h-a.performanceTime/1E3+a.contextTime):h=h-performance.now()/1E3+this._audioContext.currentTime);this._lastPlayedTag=g;this._AddPendingTag(g);try{this._lastAudioInstance=await this._GetAudioInstance(b,c,d,g,e),f?(this._lastAudioInstance.SetPannerEnabled(!0),
this._lastAudioInstance.SetPan(f.x,f.y,f.angle,f.innerAngle,f.outerAngle,f.outerGain),f.hasOwnProperty("uid")&&this._lastAudioInstance.SetUID(f.uid)):this._lastAudioInstance.SetPannerEnabled(!1),this._lastAudioInstance.Play(k,l,m,h)}catch(n){console.error("[Construct 3] Audio: error starting playback: ",n);return}finally{this._RemovePendingTag(g)}this._StartTicking()}_Stop(a){a=a.tag;for(const b of this.audioInstancesByTag(a))b.Stop()}_StopAll(){for(const a of this._audioInstances)a.Stop()}_SetPaused(a){const b=
a.tag;a=a.paused;for(const c of this.audioInstancesByTag(b))a?c.Pause():c.Resume();this._MaybeStartTicking()}_SetVolume(a){const b=a.tag;a=a.vol;for(const c of this.audioInstancesByTag(b))c.SetVolume(a)}async _FadeVolume(a){const b=a.tag,c=a.vol,d=a.duration;a=a.stopOnEnd;await this.TagReady(b);for(const e of this.audioInstancesByTag(b))e.FadeVolume(c,d,a);this._MaybeStartTicking()}_SetMasterVolume(a){this._masterVolume=a.vol;for(const a of this._audioInstances)a._UpdateVolume()}_SetMuted(a){const b=
a.tag;a=a.isMuted;for(const c of this.audioInstancesByTag(b))c.SetMuted(a)}_SetSilent(a){this._isSilent=a.isSilent;this._iRuntime.SetSilent(this._isSilent);for(const a of this._audioInstances)a._UpdateMuted()}_SetLooping(a){const b=a.tag;a=a.isLooping;for(const c of this.audioInstancesByTag(b))c.SetLooping(a)}async _SetPlaybackRate(a){const b=a.tag;a=a.rate;await this.TagReady(b);for(const c of this.audioInstancesByTag(b))c.SetPlaybackRate(a)}async _Seek(a){const b=a.tag;a=a.pos;await this.TagReady(b);
for(const c of this.audioInstancesByTag(b))c.Seek(a)}async _Preload(a){const b=a.originalUrl,c=a.url,d=a.type;a=a.isMusic;try{await this._GetAudioInstance(b,c,d,"",a)}catch(e){console.error("[Construct 3] Audio: error preloading: ",e)}}async _Unload(a){if(a=await this._GetAudioBuffer("",a.url,a.type,a.isMusic,!0))a.Release(),a=this._audioBuffers.indexOf(a),-1!==a&&this._audioBuffers.splice(a,1)}_UnloadAll(){for(const a of this._audioBuffers)a.Release();this._audioBuffers.length=0}_SetSuspended(a){a=
a.isSuspended;!a&&this._audioContext.resume&&this._audioContext.resume();for(const b of this._audioInstances)b.SetSuspended(a);a&&this._audioContext.suspend&&this._audioContext.suspend()}_OnTick(a){this._timeScale=a.timeScale;this._gameTime=a.gameTime;this._lastTickCount=a.tickCount;if(0!==this._timeScaleMode)for(var b of this._audioInstances)b._UpdatePlaybackRate();(b=a.listenerPos)&&this._audioContext.listener.setPosition(b[0],b[1],b[2]);for(const b of a.instPans){a=b.uid;for(const c of this._audioInstances)c.GetUID()===
a&&c.SetPanXYA(b.x,b.y,b.angle)}}async _AddEffect(a){var b=a.type;const c=a.tag;var d=a.params;if("filter"===b)d=new self.C3AudioFilterFX(this,...d);else if("delay"===b)d=new self.C3AudioDelayFX(this,...d);else if("convolution"===b){b=null;try{b=await this._GetAudioBuffer(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(e){console.log("[Construct 3] Audio: error loading convolution: ",e);return}d=new self.C3AudioConvolveFX(this,b.GetAudioBuffer(),...d);d._SetBufferInfo(a.bufferOriginalUrl,a.bufferUrl,
a.bufferType)}else if("flanger"===b)d=new self.C3AudioFlangerFX(this,...d);else if("phaser"===b)d=new self.C3AudioPhaserFX(this,...d);else if("gain"===b)d=new self.C3AudioGainFX(this,...d);else if("tremolo"===b)d=new self.C3AudioTremoloFX(this,...d);else if("ringmod"===b)d=new self.C3AudioRingModFX(this,...d);else if("distortion"===b)d=new self.C3AudioDistortionFX(this,...d);else if("compressor"===b)d=new self.C3AudioCompressorFX(this,...d);else if("analyser"===b)d=new self.C3AudioAnalyserFX(this,
...d);else throw Error("invalid effect type");this.AddEffectForTag(c,d);this._PostUpdatedFxState()}_SetEffectParam(a){const b=a.index,c=a.param,d=a.value,e=a.ramp,g=a.time;a=this._effects.get(a.tag);!a||0>b||b>=a.length||(a[b].SetParam(c,d,e,g),this._PostUpdatedFxState())}_RemoveEffects(a){a=a.tag.toLowerCase();const b=this._effects.get(a);if(b&&b.length){for(const a of b)a.Release();this._effects.delete(a);this._ReconnectEffects(a)}}_AddAnalyser(a){this._analysers.add(a);this._MaybeStartTicking()}_RemoveAnalyser(a){this._analysers.delete(a)}_PostUpdatedFxState(){this._isPendingPostFxState||
(this._isPendingPostFxState=!0,Promise.resolve().then(()=>this._DoPostUpdatedFxState()))}_DoPostUpdatedFxState(){const a={};for(const [b,c]of this._effects)a[b]=c.map(a=>a.GetState());this.PostToRuntime("fxstate",{fxstate:a});this._isPendingPostFxState=!1}async _OnLoadState(a){const b=a.saveLoadMode;if(3!==b)for(var c of this._audioInstances)c.IsMusic()&&1===b||(c.IsMusic()||2!==b)&&c.Stop();for(const a of this._effects.values())for(const b of a)b.Release();this._effects.clear();this._timeScale=a.timeScale;
this._gameTime=a.gameTime;c=a.listenerPos;this._audioContext.listener.setPosition(c[0],c[1],c[2]);this._isSilent=a.isSilent;this._iRuntime.SetSilent(this._isSilent);this._masterVolume=a.masterVolume;c=[];for(const b of Object.values(a.effects))c.push(Promise.all(b.map(a=>this._AddEffect(a))));await Promise.all(c);await Promise.all(a.playing.map(a=>this._LoadAudioInstance(a,b)));this._MaybeStartTicking()}async _LoadAudioInstance(a,b){if(3!==b){var c=a.bufferOriginalUrl,d=a.bufferUrl,e=a.bufferType,
g=a.isMusic,k=a.tag,l=a.isLooping,m=a.volume,f=a.playbackTime;if(!g||1!==b)if(g||2!==b){b=null;try{b=await this._GetAudioInstance(c,d,e,k,g)}catch(h){console.error("[Construct 3] Audio: error loading audio state: ",h);return}b.LoadPanState(a.pan);b.Play(l,m,f,0);a.isPlaying||b.Pause();b._LoadAdditionalState(a)}}}_OnMicrophoneStream(a,b){this._microphoneSource&&this._microphoneSource.disconnect();this._microphoneTag=b.toLowerCase();this._microphoneSource=this._audioContext.createMediaStreamSource(a);
this._microphoneSource.connect(this.GetDestinationForTag(this._microphoneTag))}_OnGetOutputStream(){this._destMediaStreamNode||(this._destMediaStreamNode=this._audioContext.createMediaStreamDestination(),this._destinationNode.connect(this._destMediaStreamNode));return this._destMediaStreamNode.stream}});
'use strict';self.C3AudioBuffer=class{constructor(a,d,e,c,b){this._audioDomHandler=a;this._originalUrl=d;this._url=e;this._type=c;this._isMusic=b;this._api="";this._loadState="not-loaded";this._loadPromise=null}Release(){this._loadState="not-loaded";this._loadPromise=this._audioDomHandler=null}static Create(a,d,e,c,b){const f="audio/webm; codecs=opus"===c&&!a.SupportsWebMOpus();b&&f&&a._SetHasAnySoftwareDecodedMusic();return!b||a.IsPlayMusicAsSound()||f?new self.C3WebAudioBuffer(a,d,e,c,b,f):new self.C3Html5AudioBuffer(a,
d,e,c,b)}CreateInstance(a){return"html5"===this._api?new self.C3Html5AudioInstance(this._audioDomHandler,this,a):new self.C3WebAudioInstance(this._audioDomHandler,this,a)}_Load(){}Load(){this._loadPromise||(this._loadPromise=this._Load());return this._loadPromise}IsLoaded(){}IsLoadedAndDecoded(){}HasFailedToLoad(){return"failed"===this._loadState}GetAudioContext(){return this._audioDomHandler.GetAudioContext()}GetApi(){return this._api}GetOriginalUrl(){return this._originalUrl}GetUrl(){return this._url}GetContentType(){return this._type}IsMusic(){return this._isMusic}GetDuration(){}};
'use strict';self.C3Html5AudioBuffer=class extends self.C3AudioBuffer{constructor(a,b,c,d,e){super(a,b,c,d,e);this._api="html5";this._audioElem=new Audio;this._audioElem.crossOrigin="anonymous";this._audioElem.autoplay=!1;this._audioElem.preload="auto";this._loadReject=this._loadResolve=null;this._reachedCanPlayThrough=!1;this._audioElem.addEventListener("canplaythrough",()=>this._reachedCanPlayThrough=!0);this._outNode=this.GetAudioContext().createGain();this._mediaSourceNode=null;this._audioElem.addEventListener("canplay",
()=>{this._loadResolve&&(this._loadState="loaded",this._loadResolve(),this._loadReject=this._loadResolve=null);!this._mediaSourceNode&&this._audioElem&&(this._mediaSourceNode=this.GetAudioContext().createMediaElementSource(this._audioElem),this._mediaSourceNode.connect(this._outNode))});this.onended=null;this._audioElem.addEventListener("ended",()=>{if(this.onended)this.onended()});this._audioElem.addEventListener("error",a=>this._OnError(a))}Release(){this._audioDomHandler.ReleaseInstancesForBuffer(this);
this._outNode.disconnect();this._outNode=null;this._mediaSourceNode.disconnect();this._mediaSourceNode=null;this._audioElem&&!this._audioElem.paused&&this._audioElem.pause();this._audioElem=this.onended=null;super.Release()}_Load(){this._loadState="loading";return new Promise((a,b)=>{this._loadResolve=a;this._loadReject=b;this._audioElem.src=this._url})}_OnError(a){console.error(`[Construct 3] Audio '${this._url}' error: `,a);this._loadReject&&(this._loadState="failed",this._loadReject(a),this._loadReject=
this._loadResolve=null)}IsLoaded(){const a=4<=this._audioElem.readyState;a&&(this._reachedCanPlayThrough=!0);return a||this._reachedCanPlayThrough}IsLoadedAndDecoded(){return this.IsLoaded()}GetAudioElement(){return this._audioElem}GetOutputNode(){return this._outNode}GetDuration(){return this._audioElem.duration}};
'use strict';self.C3WebAudioBuffer=class extends self.C3AudioBuffer{constructor(a,b,c,d,e,f){super(a,b,c,d,e);this._api="webaudio";this._audioBuffer=this._audioData=null;this._needsSoftwareDecode=!!f}Release(){this._audioDomHandler.ReleaseInstancesForBuffer(this);this._audioBuffer=this._audioData=null;super.Release()}async _Fetch(){if(this._audioData)return this._audioData;var a=this._audioDomHandler.GetRuntimeInterface();if("cordova"===a.GetExportType()&&a.IsRelativeURL(this._url)&&"file:"===location.protocol)this._audioData=
await a.CordovaFetchLocalFileAsArrayBuffer(this._url);else{a=await fetch(this._url);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);this._audioData=await a.arrayBuffer()}}async _Decode(){if(this._audioBuffer)return this._audioBuffer;this._audioBuffer=await this._audioDomHandler.DecodeAudioData(this._audioData,this._needsSoftwareDecode);this._audioData=null}async _Load(){try{this._loadState="loading",await this._Fetch(),await this._Decode(),this._loadState="loaded"}catch(a){this._loadState=
"failed",console.error(`[Construct 3] Failed to load audio '${this._url}': `,a)}}IsLoaded(){return!(!this._audioData&&!this._audioBuffer)}IsLoadedAndDecoded(){return!!this._audioBuffer}GetAudioBuffer(){return this._audioBuffer}GetDuration(){return this._audioBuffer?this._audioBuffer.duration:0}};
'use strict';{var toDegrees=function(a){return a*f};const f=180/Math.PI;let g=0;self.C3AudioInstance=class{constructor(a,b,c){this._audioDomHandler=a;this._buffer=b;this._tag=c;this._aiId=g++;this._gainNode=this.GetAudioContext().createGain();this._gainNode.connect(this.GetDestinationNode());this._pannerNode=null;this._isPannerEnabled=!1;this._isStopped=!0;this._isLooping=this._resumeMe=this._isPaused=!1;this._volume=1;this._isMuted=!1;this._playbackRate=1;a=this._audioDomHandler.GetTimeScaleMode();
this._isTimescaled=1===a&&!this.IsMusic()||2===a;this._fadeEndTime=this._instUid=-1;this._stopOnFadeEnd=!1}Release(){this._buffer=this._audioDomHandler=null;this._pannerNode&&(this._pannerNode.disconnect(),this._pannerNode=null);this._gainNode.disconnect();this._gainNode=null}GetAudioContext(){return this._audioDomHandler.GetAudioContext()}GetDestinationNode(){return this._audioDomHandler.GetDestinationForTag(this._tag)}GetMasterVolume(){return this._audioDomHandler.GetMasterVolume()}GetCurrentTime(){return this._isTimescaled?
this._audioDomHandler.GetGameTime():performance.now()/1E3}GetOriginalUrl(){return this._buffer.GetOriginalUrl()}GetUrl(){return this._buffer.GetUrl()}GetContentType(){return this._buffer.GetContentType()}GetBuffer(){return this._buffer}IsMusic(){return this._buffer.IsMusic()}SetTag(a){this._tag=a}GetTag(){return this._tag}GetAiId(){return this._aiId}HasEnded(){}CanBeRecycled(){}IsPlaying(){return!this._isStopped&&!this._isPaused&&!this.HasEnded()}IsActive(){return!this._isStopped&&!this.HasEnded()}GetPlaybackTime(a){}GetDuration(a){let b=
this._buffer.GetDuration();a&&(b/=this._playbackRate||.001);return b}Play(a,b,c,d){}Stop(){}Pause(){}IsPaused(){return this._isPaused}Resume(){}SetVolume(a){this._volume=a;this._gainNode.gain.cancelScheduledValues(0);this._fadeEndTime=-1;this._gainNode.gain.value=this.GetOverallVolume()}FadeVolume(a,b,c){if(!this.IsMuted()){a*=this.GetMasterVolume();var d=this._gainNode.gain;d.cancelScheduledValues(0);var e=this._audioDomHandler.GetAudioCurrentTime();b=e+b;d.setValueAtTime(d.value,e);d.linearRampToValueAtTime(a,
b);this._volume=a;this._fadeEndTime=b;this._stopOnFadeEnd=c}}_UpdateVolume(){this.SetVolume(this._volume)}Tick(a){-1!==this._fadeEndTime&&a>=this._fadeEndTime&&(this._fadeEndTime=-1,this._stopOnFadeEnd&&this.Stop(),this._audioDomHandler.PostTrigger("fade-ended",this._tag,this._aiId))}GetOverallVolume(){const a=this._volume*this.GetMasterVolume();return isFinite(a)?a:0}SetMuted(a){a=!!a;this._isMuted!==a&&(this._isMuted=a,this._UpdateMuted())}IsMuted(){return this._isMuted}IsSilent(){return this._audioDomHandler.IsSilent()}_UpdateMuted(){}SetLooping(a){}IsLooping(){return this._isLooping}SetPlaybackRate(a){this._playbackRate!==
a&&(this._playbackRate=a,this._UpdatePlaybackRate())}_UpdatePlaybackRate(){}GetPlaybackRate(){return this._playbackRate}Seek(a){}SetSuspended(a){}SetPannerEnabled(a){a=!!a;this._isPannerEnabled!==a&&((this._isPannerEnabled=a)?(this._pannerNode||(this._pannerNode=this.GetAudioContext().createPanner(),this._pannerNode.panningModel=this._audioDomHandler.GetPanningModel(),this._pannerNode.distanceModel=this._audioDomHandler.GetDistanceModel(),this._pannerNode.refDistance=this._audioDomHandler.GetReferenceDistance(),
this._pannerNode.maxDistance=this._audioDomHandler.GetMaxDistance(),this._pannerNode.rolloffFactor=this._audioDomHandler.GetRolloffFactor()),this._gainNode.disconnect(),this._gainNode.connect(this._pannerNode),this._pannerNode.connect(this.GetDestinationNode())):(this._pannerNode.disconnect(),this._gainNode.disconnect(),this._gainNode.connect(this.GetDestinationNode())))}SetPan(a,b,c,d,e,h){this._isPannerEnabled&&(this.SetPanXYA(a,b,c),this._pannerNode.coneInnerAngle=toDegrees(d),this._pannerNode.coneOuterAngle=
toDegrees(e),this._pannerNode.coneOuterGain=h)}SetPanXYA(a,b,c){this._isPannerEnabled&&(this._pannerNode.setPosition(a,b,0),this._pannerNode.setOrientation(Math.cos(c),Math.sin(c),0))}SetUID(a){this._instUid=a}GetUID(){return this._instUid}GetResumePosition(){}Reconnect(a){const b=this._pannerNode||this._gainNode;b.disconnect();b.connect(a)}GetState(){return{aiid:this.GetAiId(),tag:this._tag,duration:this.GetDuration(),volume:this._volume,isPlaying:this.IsPlaying(),playbackTime:this.GetPlaybackTime(),
playbackRate:this.GetPlaybackRate(),uid:this._instUid,bufferOriginalUrl:this.GetOriginalUrl(),bufferUrl:"",bufferType:this.GetContentType(),isMusic:this.IsMusic(),isLooping:this.IsLooping(),isMuted:this.IsMuted(),resumePosition:this.GetResumePosition(),pan:this.GetPanState()}}_LoadAdditionalState(a){this.SetPlaybackRate(a.playbackRate);this.SetMuted(a.isMuted)}GetPanState(){if(!this._pannerNode)return null;const a=this._pannerNode;return{pos:[a.positionX.value,a.positionY.value,a.positionZ.value],
orient:[a.orientationX.value,a.orientationY.value,a.orientationZ.value],cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this._instUid}}LoadPanState(a){a?(this.SetPannerEnabled(!0),a=this._pannerNode,a.setPosition(...a.pos),a.setOrientation(...a.orient),a.coneInnerAngle=a.cia,a.coneOuterAngle=a.coa,a.coneOuterGain=a.cog,this._instUid=a.uid):this.SetPannerEnabled(!1)}}};
'use strict';self.C3Html5AudioInstance=class extends self.C3AudioInstance{constructor(a,b,d){super(a,b,d);this._buffer.GetOutputNode().connect(this._gainNode);this._buffer.onended=()=>this._OnEnded()}Release(){this.Stop();this._buffer.GetOutputNode().disconnect();super.Release()}GetAudioElement(){return this._buffer.GetAudioElement()}_OnEnded(){this._isStopped=!0;this._instUid=-1;this._audioDomHandler.PostTrigger("ended",this._tag,this._aiId)}HasEnded(){return this.GetAudioElement().ended}CanBeRecycled(){return this._isStopped?
!0:this.HasEnded()}GetPlaybackTime(a){let b=this.GetAudioElement().currentTime;a&&(b*=this._playbackRate);this._isLooping||(b=Math.min(b,this.GetDuration()));return b}Play(a,b,d,c){c=this.GetAudioElement();1!==c.playbackRate&&(c.playbackRate=1);c.loop!==a&&(c.loop=a);this.SetVolume(b);c.muted&&(c.muted=!1);if(c.currentTime!==d)try{c.currentTime=d}catch(e){console.warn(`[Construct 3] Exception seeking audio '${this._buffer.GetUrl()}' to position '${d}': `,e)}this._audioDomHandler.TryPlayMedia(c);this._isPaused=
this._isStopped=!1;this._isLooping=a;this._playbackRate=1}Stop(){const a=this.GetAudioElement();a.paused||a.pause();this._audioDomHandler.RemovePendingPlay(a);this._isStopped=!0;this._isPaused=!1;this._instUid=-1}Pause(){if(!(this._isPaused||this._isStopped||this.HasEnded())){var a=this.GetAudioElement();a.paused||a.pause();this._audioDomHandler.RemovePendingPlay(a);this._isPaused=!0}}Resume(){!this._isPaused||this._isStopped||this.HasEnded()||(this._audioDomHandler.TryPlayMedia(this.GetAudioElement()),
this._isPaused=!1)}_UpdateMuted(){this.GetAudioElement().muted=this._isMuted||this.IsSilent()}SetLooping(a){a=!!a;this._isLooping!==a&&(this._isLooping=a,this.GetAudioElement().loop=a)}_UpdatePlaybackRate(){let a=this._playbackRate;this._isTimescaled&&(a*=this._audioDomHandler.GetTimeScale());try{this.GetAudioElement().playbackRate=a}catch(b){console.warn(`[Construct 3] Unable to set playback rate '${a}':`,b)}}Seek(a){if(!this._isStopped&&!this.HasEnded())try{this.GetAudioElement().currentTime=a}catch(b){console.warn(`[Construct 3] Error seeking audio to '${a}': `,
b)}}GetResumePosition(){return this.GetPlaybackTime()}SetSuspended(a){a?this.IsPlaying()?(this.GetAudioElement().pause(),this._resumeMe=!0):this._resumeMe=!1:this._resumeMe&&(this._audioDomHandler.TryPlayMedia(this.GetAudioElement()),this._resumeMe=!1)}};
'use strict';self.C3WebAudioInstance=class extends self.C3AudioInstance{constructor(a,b,c){super(a,b,c);this._bufferSource=null;this._onended_handler=a=>this._OnEnded(a);this._hasPlaybackEnded=!0;this._activeSource=null;this._resumePosition=this._startTime=0;this._muteVol=1}Release(){this.Stop();this._ReleaseBufferSource();this._onended_handler=null;super.Release()}_ReleaseBufferSource(){this._bufferSource&&this._bufferSource.disconnect();this._activeSource=this._bufferSource=null}_OnEnded(a){this._isPaused||
this._resumeMe||a.target!==this._activeSource||(this._isStopped=this._hasPlaybackEnded=!0,this._instUid=-1,this._ReleaseBufferSource(),this._audioDomHandler.PostTrigger("ended",this._tag,this._aiId))}HasEnded(){return!this._isStopped&&this._bufferSource&&this._bufferSource.loop||this._isPaused?!1:this._hasPlaybackEnded}CanBeRecycled(){return!this._bufferSource||this._isStopped?!0:this.HasEnded()}GetPlaybackTime(a){let b;b=this._isPaused?this._resumePosition:this.GetCurrentTime()-this._startTime;a&&
(b*=this._playbackRate);this._isLooping||(b=Math.min(b,this.GetDuration()));return b}Play(a,b,c,d){this._muteVol=1;this.SetVolume(b);this._ReleaseBufferSource();this._bufferSource=this.GetAudioContext().createBufferSource();this._bufferSource.buffer=this._buffer.GetAudioBuffer();this._bufferSource.connect(this._gainNode);this._activeSource=this._bufferSource;this._bufferSource.onended=this._onended_handler;this._bufferSource.loop=a;this._bufferSource.start(d,c);this._isPaused=this._isStopped=this._hasPlaybackEnded=
!1;this._isLooping=a;this._playbackRate=1;this._startTime=this.GetCurrentTime()-c}Stop(){if(this._bufferSource)try{this._bufferSource.stop(0)}catch(a){}this._isStopped=!0;this._isPaused=!1;this._instUid=-1}Pause(){this._isPaused||this._isStopped||this.HasEnded()||(this._resumePosition=this.GetPlaybackTime(!0),this._isLooping&&(this._resumePosition%=this.GetDuration()),this._isPaused=!0,this._bufferSource.stop(0))}Resume(){!this._isPaused||this._isStopped||this.HasEnded()||(this._ReleaseBufferSource(),
this._bufferSource=this.GetAudioContext().createBufferSource(),this._bufferSource.buffer=this._buffer.GetAudioBuffer(),this._bufferSource.connect(this._gainNode),this._activeSource=this._bufferSource,this._bufferSource.onended=this._onended_handler,this._bufferSource.loop=this._isLooping,this._UpdateVolume(),this._UpdatePlaybackRate(),this._startTime=this.GetCurrentTime()-this._resumePosition/(this._playbackRate||.001),this._bufferSource.start(0,this._resumePosition),this._isPaused=!1)}GetOverallVolume(){return super.GetOverallVolume()*
this._muteVol}_UpdateMuted(){this._muteVol=this._isMuted||this.IsSilent()?0:1;this._UpdateVolume()}SetLooping(a){a=!!a;this._isLooping!==a&&(this._isLooping=a,this._bufferSource&&(this._bufferSource.loop=a))}_UpdatePlaybackRate(){let a=this._playbackRate;this._isTimescaled&&(a*=this._audioDomHandler.GetTimeScale());this._bufferSource&&(this._bufferSource.playbackRate.value=a)}Seek(a){this._isStopped||this.HasEnded()||(this._isPaused?this._resumePosition=a:(this.Pause(),this._resumePosition=a,this.Resume()))}GetResumePosition(){return this._resumePosition}SetSuspended(a){a?
this.IsPlaying()?(this._resumeMe=!0,this._resumePosition=this.GetPlaybackTime(!0),this._isLooping&&(this._resumePosition%=this.GetDuration()),this._bufferSource.stop(0)):this._resumeMe=!1:this._resumeMe&&(this._ReleaseBufferSource(),this._bufferSource=this.GetAudioContext().createBufferSource(),this._bufferSource.buffer=this._buffer.GetAudioBuffer(),this._bufferSource.connect(this._gainNode),this._activeSource=this._bufferSource,this._bufferSource.onended=this._onended_handler,this._bufferSource.loop=
this._isLooping,this._UpdateVolume(),this._UpdatePlaybackRate(),this._startTime=this.GetCurrentTime()-this._resumePosition/(this._playbackRate||.001),this._bufferSource.start(0,this._resumePosition),this._resumeMe=!1)}_LoadAdditionalState(a){super._LoadAdditionalState(a);this._resumePosition=a.resumePosition}};
'use strict';{var e4=function(b,a){return 1-Math.exp(-a*b)},LinearToDb=function(b){return LinearToDbNoCap(Math.max(Math.min(b,1),0))},LinearToDbNoCap=function(b){return Math.log(b)/Math.log(10)*20},DbToLinear=function(b){return Math.max(Math.min(DbToLinearNoCap(b),1),0)},DbToLinearNoCap=function(b){return Math.pow(10,b/20)};class g{constructor(b){this._audioDomHandler=b;this._audioContext=b.GetAudioContext();this._index=-1;this._type=this._tag="";this._params=null}Release(){this._audioContext=null}_SetIndex(b){this._index=
b}GetIndex(){return this._index}_SetTag(b){this._tag=b}GetTag(){return this._tag}CreateGain(){return this._audioContext.createGain()}GetInputNode(){}ConnectTo(b){}SetAudioParam(b,a,c,d){b.cancelScheduledValues(0);if(0===d)b.value=a;else{var e=this._audioContext.currentTime;d+=e;switch(c){case 0:b.setValueAtTime(a,d);break;case 1:b.setValueAtTime(b.value,e);b.linearRampToValueAtTime(a,d);break;case 2:b.setValueAtTime(b.value,e),b.exponentialRampToValueAtTime(a,d)}}}GetState(){return{type:this._type,
tag:this._tag,params:this._params}}}self.C3AudioFilterFX=class extends g{constructor(b,a,c,d,e,f,h){super(b);this._type="filter";this._params=[a,c,d,e,f,h];this._inputNode=this.CreateGain();this._wetNode=this.CreateGain();this._wetNode.gain.value=h;this._dryNode=this.CreateGain();this._dryNode.gain.value=1-h;this._filterNode=this._audioContext.createBiquadFilter();this._filterNode.type=a;this._filterNode.frequency.value=c;this._filterNode.detune.value=d;this._filterNode.Q.value=e;this._filterNode.gain.vlaue=
f;this._inputNode.connect(this._filterNode);this._inputNode.connect(this._dryNode);this._filterNode.connect(this._wetNode)}Release(){this._inputNode.disconnect();this._filterNode.disconnect();this._wetNode.disconnect();this._dryNode.disconnect();super.Release()}ConnectTo(b){this._wetNode.disconnect();this._wetNode.connect(b);this._dryNode.disconnect();this._dryNode.connect(b)}GetInputNode(){return this._inputNode}SetParam(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this._params[5]=a;
this.SetAudioParam(this._wetNode.gain,a,c,d);this.SetAudioParam(this._dryNode.gain,1-a,c,d);break;case 1:this._params[1]=a;this.SetAudioParam(this._filterNode.frequency,a,c,d);break;case 2:this._params[2]=a;this.SetAudioParam(this._filterNode.detune,a,c,d);break;case 3:this._params[3]=a;this.SetAudioParam(this._filterNode.Q,a,c,d);break;case 4:this._params[4]=a,this.SetAudioParam(this._filterNode.gain,a,c,d)}}};self.C3AudioDelayFX=class extends g{constructor(b,a,c,d){super(b);this._type="delay";this._params=
[a,c,d];this._inputNode=this.CreateGain();this._wetNode=this.CreateGain();this._wetNode.gain.value=d;this._dryNode=this.CreateGain();this._dryNode.gain.value=1-d;this._mainNode=this.CreateGain();this._delayNode=this._audioContext.createDelay(a);this._delayNode.delayTime.value=a;this._delayGainNode=this.CreateGain();this._delayGainNode.gain.value=c;this._inputNode.connect(this._mainNode);this._inputNode.connect(this._dryNode);this._mainNode.connect(this._wetNode);this._mainNode.connect(this._delayNode);
this._delayNode.connect(this._delayGainNode);this._delayGainNode.connect(this._mainNode)}Release(){this._inputNode.disconnect();this._wetNode.disconnect();this._dryNode.disconnect();this._mainNode.disconnect();this._delayNode.disconnect();this._delayGainNode.disconnect();super.Release()}ConnectTo(b){this._wetNode.disconnect();this._wetNode.connect(b);this._dryNode.disconnect();this._dryNode.connect(b)}GetInputNode(){return this._inputNode}SetParam(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,
1),0);this._params[2]=a;this.SetAudioParam(this._wetNode.gain,a,c,d);this.SetAudioParam(this._dryNode.gain,1-a,c,d);break;case 4:this._params[1]=DbToLinear(a);this.SetAudioParam(this._delayGainNode.gain,DbToLinear(a),c,d);break;case 5:this._params[0]=a,this.SetAudioParam(this._delayNode.delayTime,a,c,d)}}};self.C3AudioConvolveFX=class extends g{constructor(b,a,c,d){super(b);this._type="convolution";this._params=[c,d];this._bufferType=this._bufferUrl=this._bufferOriginalUrl="";this._inputNode=this.CreateGain();
this._wetNode=this.CreateGain();this._wetNode.gain.value=d;this._dryNode=this.CreateGain();this._dryNode.gain.value=1-d;this._convolveNode=this._audioContext.createConvolver();this._convolveNode.normalize=c;this._convolveNode.buffer=a;this._inputNode.connect(this._convolveNode);this._inputNode.connect(this._dryNode);this._convolveNode.connect(this._wetNode)}Release(){this._inputNode.disconnect();this._convolveNode.disconnect();this._wetNode.disconnect();this._dryNode.disconnect();super.Release()}ConnectTo(b){this._wetNode.disconnect();
this._wetNode.connect(b);this._dryNode.disconnect();this._dryNode.connect(b)}GetInputNode(){return this._inputNode}SetParam(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this._params[1]=a,this.SetAudioParam(this._wetNode.gain,a,c,d),this.SetAudioParam(this._dryNode.gain,1-a,c,d)}}_SetBufferInfo(b,a,c){this._bufferOriginalUrl=b;this._bufferUrl=a;this._bufferType=c}GetState(){const b=super.GetState();b.bufferOriginalUrl=this._bufferOriginalUrl;b.bufferUrl="";b.bufferType=this._bufferType;
return b}};self.C3AudioFlangerFX=class extends g{constructor(b,a,c,d,e,f){super(b);this._type="flanger";this._params=[a,c,d,e,f];this._inputNode=this.CreateGain();this._dryNode=this.CreateGain();this._dryNode.gain.value=1-f/2;this._wetNode=this.CreateGain();this._wetNode.gain.value=f/2;this._feedbackNode=this.CreateGain();this._feedbackNode.gain.value=e;this._delayNode=this._audioContext.createDelay(a+c);this._delayNode.delayTime.value=a;this._oscNode=this._audioContext.createOscillator();this._oscNode.frequency.value=
d;this._oscGainNode=this.CreateGain();this._oscGainNode.gain.value=c;this._inputNode.connect(this._delayNode);this._inputNode.connect(this._dryNode);this._delayNode.connect(this._wetNode);this._delayNode.connect(this._feedbackNode);this._feedbackNode.connect(this._delayNode);this._oscNode.connect(this._oscGainNode);this._oscGainNode.connect(this._delayNode.delayTime);this._oscNode.start(0)}Release(){this._oscNode.stop(0);this._inputNode.disconnect();this._delayNode.disconnect();this._oscNode.disconnect();
this._oscGainNode.disconnect();this._dryNode.disconnect();this._wetNode.disconnect();this._feedbackNode.disconnect();super.Release()}ConnectTo(b){this._wetNode.disconnect();this._wetNode.connect(b);this._dryNode.disconnect();this._dryNode.connect(b)}GetInputNode(){return this._inputNode}SetParam(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this._params[4]=a;this.SetAudioParam(this._wetNode.gain,a/2,c,d);this.SetAudioParam(this._dryNode.gain,1-a/2,c,d);break;case 6:this._params[1]=a/1E3;
this.SetAudioParam(this._oscGainNode.gain,a/1E3,c,d);break;case 7:this._params[2]=a;this.SetAudioParam(this._oscNode.frequency,a,c,d);break;case 8:this._params[3]=a/100,this.SetAudioParam(this._feedbackNode.gain,a/100,c,d)}}};self.C3AudioPhaserFX=class extends g{constructor(b,a,c,d,e,f,h){super(b);this._type="phaser";this._params=[a,c,d,e,f,h];this._inputNode=this.CreateGain();this._dryNode=this.CreateGain();this._dryNode.gain.value=1-h/2;this._wetNode=this.CreateGain();this._wetNode.gain.value=h/
2;this._filterNode=this._audioContext.createBiquadFilter();this._filterNode.type="allpass";this._filterNode.frequency.value=a;this._filterNode.detune.value=c;this._filterNode.Q.value=d;this._oscNode=this._audioContext.createOscillator();this._oscNode.frequency.value=f;this._oscGainNode=this.CreateGain();this._oscGainNode.gain.value=e;this._inputNode.connect(this._filterNode);this._inputNode.connect(this._dryNode);this._filterNode.connect(this._wetNode);this._oscNode.connect(this._oscGainNode);this._oscGainNode.connect(this._filterNode.frequency);
this._oscNode.start(0)}Release(){this._oscNode.stop(0);this._inputNode.disconnect();this._filterNode.disconnect();this._oscNode.disconnect();this._oscGainNode.disconnect();this._dryNode.disconnect();this._wetNode.disconnect();super.Release()}ConnectTo(b){this._wetNode.disconnect();this._wetNode.connect(b);this._dryNode.disconnect();this._dryNode.connect(b)}GetInputNode(){return this._inputNode}SetParam(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this._params[5]=a;this.SetAudioParam(this._wetNode.gain,
a/2,c,d);this.SetAudioParam(this._dryNode.gain,1-a/2,c,d);break;case 1:this._params[0]=a;this.SetAudioParam(this._filterNode.frequency,a,c,d);break;case 2:this._params[1]=a;this.SetAudioParam(this._filterNode.detune,a,c,d);break;case 3:this._params[2]=a;this.SetAudioParam(this._filterNode.Q,a,c,d);break;case 6:this._params[3]=a;this.SetAudioParam(this._oscGainNode.gain,a,c,d);break;case 7:this._params[4]=a,this.SetAudioParam(this._oscNode.frequency,a,c,d)}}};self.C3AudioGainFX=class extends g{constructor(b,
a){super(b);this._type="gain";this._params=[a];this._node=this.CreateGain();this._node.gain.value=a}Release(){this._node.disconnect();super.Release()}ConnectTo(b){this._node.disconnect();this._node.connect(b)}GetInputNode(){return this._node}SetParam(b,a,c,d){switch(b){case 4:this._params[0]=DbToLinear(a),this.SetAudioParam(this._node.gain,DbToLinear(a),c,d)}}};self.C3AudioTremoloFX=class extends g{constructor(b,a,c){super(b);this._type="tremolo";this._params=[a,c];this._node=this.CreateGain();this._node.gain.value=
1-c/2;this._oscNode=this._audioContext.createOscillator();this._oscNode.frequency.value=a;this._oscGainNode=this.CreateGain();this._oscGainNode.gain.value=c/2;this._oscNode.connect(this._oscGainNode);this._oscGainNode.connect(this._node.gain);this._oscNode.start(0)}Release(){this._oscNode.stop(0);this._oscNode.disconnect();this._oscGainNode.disconnect();this._node.disconnect();super.Release()}ConnectTo(b){this._node.disconnect();this._node.connect(b)}GetInputNode(){return this._node}SetParam(b,a,
c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this._params[1]=a;this.SetAudioParam(this._node.gain.value,1-a/2,c,d);this.SetAudioParam(this._oscGainNode.gain.value,a/2,c,d);break;case 7:this._params[0]=a,this.SetAudioParam(this._oscNode.frequency,a,c,d)}}};self.C3AudioRingModFX=class extends g{constructor(b,a,c){super(b);this._type="ringmod";this._params=[a,c];this._inputNode=this.CreateGain();this._wetNode=this.CreateGain();this._wetNode.gain.value=c;this._dryNode=this.CreateGain();this._dryNode.gain.value=
1-c;this._ringNode=this.CreateGain();this._ringNode.gain.value=0;this._oscNode=this._audioContext.createOscillator();this._oscNode.frequency.value=a;this._oscNode.connect(this._ringNode.gain);this._oscNode.start(0);this._inputNode.connect(this._ringNode);this._inputNode.connect(this._dryNode);this._ringNode.connect(this._wetNode)}Release(){this._oscNode.stop(0);this._oscNode.disconnect();this._ringNode.disconnect();this._inputNode.disconnect();this._wetNode.disconnect();this._dryNode.disconnect();
super.Release()}ConnectTo(b){this._wetNode.disconnect();this._wetNode.connect(b);this._dryNode.disconnect();this._dryNode.connect(b)}GetInputNode(){return this._inputNode}SetParam(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this._params[1]=a;this.SetAudioParam(this._wetNode.gain,a,c,d);this.SetAudioParam(this._dryNode.gain,1-a,c,d);break;case 7:this._params[0]=a,this.SetAudioParam(this._oscNode.frequency,a,c,d)}}};self.C3AudioDistortionFX=class extends g{constructor(b,a,c,d,e,f){super(b);
this._type="distortion";this._params=[a,c,d,e,f];this._inputNode=this.CreateGain();this._preGain=this.CreateGain();this._postGain=this.CreateGain();this._SetDrive(d,e);this._wetNode=this.CreateGain();this._wetNode.gain.value=f;this._dryNode=this.CreateGain();this._dryNode.gain.value=1-f;this._waveShaper=this._audioContext.createWaveShaper();this._curve=new Float32Array(65536);this._GenerateColortouchCurve(a,c);this._waveShaper.curve=this._curve;this._inputNode.connect(this._preGain);this._inputNode.connect(this._dryNode);
this._preGain.connect(this._waveShaper);this._waveShaper.connect(this._postGain);this._postGain.connect(this._wetNode)}Release(){this._inputNode.disconnect();this._preGain.disconnect();this._waveShaper.disconnect();this._postGain.disconnect();this._wetNode.disconnect();this._dryNode.disconnect();super.Release()}_SetDrive(b,a){.01>b&&(b=.01);this._preGain.gain.value=b;this._postGain.gain.value=Math.pow(1/b,.6)*a}_GenerateColortouchCurve(b,a){for(let c=0;32768>c;++c){let d=c/32768;d=this._Shape(d,b,
a);this._curve[32768+c]=d;this._curve[32768-c-1]=-d}}_Shape(b,a,c){c=1.05*c*a-a;const d=0>b?-1:1;b=0>b?-b:b;return(b<a?b:a+c*e4(b-a,1/c))*d}ConnectTo(b){this._wetNode.disconnect();this._wetNode.connect(b);this._dryNode.disconnect();this._dryNode.connect(b)}GetInputNode(){return this._inputNode}SetParam(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this._params[4]=a,this.SetAudioParam(this._wetNode.gain,a,c,d),this.SetAudioParam(this._dryNode.gain,1-a,c,d)}}};self.C3AudioCompressorFX=class extends g{constructor(b,
a,c,d,e,f){super(b);this._type="compressor";this._params=[a,c,d,e,f];this._node=this._audioContext.createDynamicsCompressor();this._node.threshold.value=a;this._node.knee.value=c;this._node.ratio.value=d;this._node.attack.value=e;this._node.release.value=f}Release(){this._node.disconnect();super.Release()}ConnectTo(b){this._node.disconnect();this._node.connect(b)}GetInputNode(){return this._node}SetParam(b,a,c,d){}};self.C3AudioAnalyserFX=class extends g{constructor(b,a,c){super(b);this._type="analyser";
this._params=[a,c];this._node=this._audioContext.createAnalyser();this._node.fftSize=a;this._node.smoothingTimeConstant=c;this._freqBins=new Float32Array(this._node.frequencyBinCount);this._signal=new Uint8Array(a);this._rms=this._peak=0;this._audioDomHandler._AddAnalyser(this)}Release(){this._audioDomHandler._RemoveAnalyser(this);this._node.disconnect();super.Release()}Tick(){this._node.getFloatFrequencyData(this._freqBins);this._node.getByteTimeDomainData(this._signal);const b=this._node.fftSize;
let a=this._peak=0;for(let c=0;c<b;++c){let b=(this._signal[c]-128)/128;0>b&&(b=-b);this._peak<b&&(this._peak=b);a+=b*b}this._peak=LinearToDb(this._peak);this._rms=LinearToDb(Math.sqrt(a/b))}ConnectTo(b){this._node.disconnect();this._node.connect(b)}GetInputNode(){return this._node}SetParam(b,a,c,d){}GetData(){return{tag:this.GetTag(),index:this.GetIndex(),peak:this._peak,rms:this._rms,binCount:this._node.frequencyBinCount,freqBins:this._freqBins}}}};
'use strict';self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMHandler{constructor(a){super(a,"mouse");this.AddRuntimeMessageHandler("cursor",a=>this._OnChangeCursorStyle(a))}_OnChangeCursorStyle(a){document.documentElement.style.cursor=a}});
